### ISSUE TITLE
AWS `source` tag should be overrideable

### ISSUE THREAD

**Issue by harryurban** [stroeer/terraform-aws-ecs-fargate#1]
All aws resources get default tags when created with this module.

When I create an ECS service via another github repository where I use `terraform-aws-buzzgate` the `source` tag should be of the service repository and not of github.com/stroeer/terraform-aws-buzzgate.

Example
in the github.com/stroeer/polyphase repo i use this module and I create aws resources with tf files, that are in the given repo. So to be able to terraform these resources you would need to know, that the tf files reside in github.com/stroeer/polyphase and not in github.com/stroeer/terraform-aws-buzzgate

**Comment by moritzzimmer** [comment]
With https://github.com/stroeer/terraform-aws-ecs-fargate/releases/tag/v0.7.0 clients can provide their own tags
