### ISSUE TITLE
Review deployment pipeline permissions

### ISSUE THREAD

**Issue by moritzzimmer** [stroeer/terraform-aws-ecs-fargate#16]
With #14 we introduced an IAM role with required permissions to run CodePipeline for services. This role currently contains commented code and it's not finally clear, which permissions are actually needed.

**Comment by thisismana** [comment]
> Task defs only support resource-level permissions `*`

[source](https://iam.cloudonaut.io/reference/ecs/RegisterTaskDefinition.html)
