### ISSUE TITLE
use newer codebuild image for faster provisioning

### ISSUE THREAD

**Issue by harryurban** [stroeer/terraform-aws-ecs-fargate#48]
# Problem Description
The `Provisioning` phase for the `CodeBuild` step currently takes several minutes, which slows down deployments of ecs tasks by a lot.

# Quick Analysis & Solution Proposal
• Currently we use `aws/codebuild/amazonlinux2-x86_64-standard:1.0`, which is pretty old.
• The Internet says that older images get dropped on the AWS caches, so we should probably switch to a newer image.
• According to this, `aws/codebuild/amazonlinux2-x86_64-standard:3.0` should be the one to to switch to:
https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

**Comment by moritzzimmer** [comment]
@harryurban would you create a pull request for this?

**Comment by thisismana** [comment]
I also wanted to revamp this codebuild with the new learnings from the docker-lambda-deployer. 
This code was migrated from the previous employee and can be optimized alot.

**Comment by harryurban** [comment]
Did I understand correctly, that you do the PR @thisismana?

**Comment by thisismana** [comment]
was fixed #50
